#!/usr/bin/bash




clamdir=/home/clamav
infectdir=/home/clamav/infected



one_r(){
	clamscan -r /home
	maldet --scan-all /
	rkhunter --check
	quarantine=`clamscan -r --move=$infected /home`
	sudo clamscan -r /home | grep FOUND >> $clamdir/report.txt
	if [ "$quarantine" ];then
		clamscan -r --remove $infectdir
		rm -rf /usr/local/maldetect/quarantine/*
		echo "Done"
	fi
}


one_s(){
	clamscan -r /home
	maldet --scan-all /
	rkhunter --check	
	quarantine=`clamscan -r --move=$infected /home`
	sudo clamscan -r /home | grep FOUND >> $report/report.txt
	echo "Files and Quarantined"
	echo "Infected Files are in => $infectdir"

	}



multi_r(){

	sudo ansible hosts -m command -a "clamscan -r /"
	sudo ansible hosts -m command -a "maldet --scan-all /"
	sudo ansible hosts -m command -a "rkhunter --check"
	sudo ansible hosts -m command -a "clamscan -r --move=/home/clamav/Infected /home"
	sudo ansible hosts -m command -a "sudo clamscan -r /home | grep FOUND >> $clamdir/report.txt"
	sudo ansible hosts -m command -a "clamscan -r --remove"
	sudo ansible hosts -m command -a "rm -rf /usr/local/maldetect/quarantine/* "

}


multi_s(){

	sudo ansible hosts -m command -a "clamscan -r /home"
	sudo ansible hosts -m command -a "maldet --scan-all /"
	sudo ansible hosts -m command -a "rkhunter --check"
	sudo ansible hosts -m command -a "clamscan -r --move=$infected /home"
	sudo ansible hosts -m command -a "clamscan -r /home | grep FOUND >> $report/report.txt"


}


menu(){
	echo "[1]- Scan Just One Server and Quarantine Infected Files"
	echo "[2]- Scan Just One Server and Remove Infected Files"
	echo "[3]- Scan Multiple Server and Quarantine Infected Files"
	echo "[4]- Scan Multiple Server and Remove Infected Files"
	echo "[5]- Exit"
	read response
	if [ "$response" = 1 ];then
		one_s
	elif [ "$reponse" = 2 ];then
		one_r
	elif [ "$response" = 3 ];then
		multi_s
	elif [ "$response" = 4 ];then
		multi_r
	elif [ "$response" = 5 ];then
		exit 0
	else
		echo "Enter valid number"
		menu
	fi


}

menu

